Feature/67 redesign home page
Social-projects-Rivne/Internet-Hospital pull request #103
Opened 2018-12-17 21:11 UTC by voznovych

2018-12-18 06:39 UTC, eugent482 approved these changes

2018-12-18 11:32 UTC, TREN-D approved these changes

2018-12-18 11:32 UTC, TREN-D commented on InternetHospital.WebApi/Controllers/ArticleController.cs
> +            return Ok(articles);
Is it okay to return ok() with arcticles if it can be null?

2018-12-18 12:34 UTC, edward0802 approved these changes

2018-12-20 12:36 UTC, OleksandrAntoniuk requested changes

2018-12-20 12:36 UTC, AntonukOM commented on InternetHospital.BusinessLogic/Services/ArticleService.cs
> +            return null;
bad practice

2018-12-20 12:36 UTC, AntonukOM commented on InternetHospital.WebApi/Controllers/ArticleController.cs
> +            var articles = _articleService.GetArticlesForHomePage(filter);
just Ok(_articleService.GetArticlesForHomePage(filter))

2018-12-20 12:55 UTC, voznovych commented on InternetHospital.BusinessLogic/Services/ArticleService.cs
> +            return null;
Than better return just empty object?

2018-12-21 09:09 UTC, OleksandrAntoniuk approved these changes

2018-12-21 09:09 UTC, AntonukOM commented on InternetHospital.BusinessLogic/Models/Articles/HomePageArticleModel.cs
> +        public DateTime DateOfCreation { get; set; }
just CreatedDate

2018-12-21 09:35 UTC, merged