Request management
Social-projects-Rivne/Internet-Hospital pull request #106
Opened 2018-12-19 14:35 UTC by martyniukroman

2018-12-19 16:12 UTC, TREN-D commented on InternetHospital.BusinessLogic/Models/FeedbackViewModel.cs
> +        public DateTime dateTime { set; get; }
Rename it

2018-12-19 16:12 UTC, TREN-D commented on InternetHospital.BusinessLogic/Services/FeedBackService.cs
> +            if (involvedUsers != null)
return involvedUsers

2018-12-19 16:12 UTC, TREN-D commented on InternetHospital.BusinessLogic/Services/FeedBackService.cs
> +            }
space

2018-12-19 16:12 UTC, TREN-D commented on InternetHospital.WebApi/Controllers/FeedBackController.cs
> +            return _feedBackService.GetUsers() == null ? (IActionResult)BadRequest(null) : Ok(_feedBackService.GetUsers());
remove null

2018-12-19 16:12 UTC, TREN-D commented on InternetHospital.WebApi/Controllers/FeedBackController.cs
> +            if (reply != null)
why no ternar?

2018-12-20 10:52 UTC, TREN-D approved these changes

2018-12-20 10:53 UTC, edward0802 approved these changes

2018-12-20 11:04 UTC, eugent482 approved these changes

2018-12-20 12:34 UTC, OleksandrAntoniuk requested changes

2018-12-20 12:34 UTC, AntonukOM commented on InternetHospital.BusinessLogic/Services/FeedBackService.cs
> +    public class FeedBackService : IFeedBackService {
format brackets

2018-12-20 12:34 UTC, AntonukOM commented on InternetHospital.BusinessLogic/Services/FeedBackService.cs
> +            try {
and here

2018-12-20 12:34 UTC, AntonukOM commented on InternetHospital.BusinessLogic/Services/FeedBackService.cs
> +            catch (Exception exception) {
everywhere please

2018-12-20 12:34 UTC, AntonukOM commented on InternetHospital.BusinessLogic/Services/FeedBackService.cs
> +            IEnumerable<UserModel> users = GetUsers(feedBacks);
just var

2018-12-20 12:34 UTC, AntonukOM commented on InternetHospital.WebApi/Controllers/FeedBackController.cs
> +            if (reply != null)
add brackets here or use ternary operator

2018-12-20 12:34 UTC, AntonukOM commented on InternetHospital.BusinessLogic/Services/FeedBackService.cs
> +        public IEnumerable<FeedBackType> GetFeedBackTypes() {
please add unit tests for this cases

2018-12-21 07:39 UTC, AntonukOM commented on InternetHospital.BusinessLogic/Services/FeedBackService.cs
> +        public IEnumerable<UserModel> GetUsers(IEnumerable<FeedBack> feedBacks) {
brackets

2018-12-21 07:39 UTC, AntonukOM commented on InternetHospital.BusinessLogic/Services/FeedBackService.cs
> +            foreach (var item in feedBacks) {
and here

2018-12-21 07:39 UTC, AntonukOM commented on InternetHospital.WebApi/Controllers/FeedBackController.cs
> +                new {
here

2018-12-21 07:39 UTC, AntonukOM commented on InternetHospital.BusinessLogic/Models/FeedBackSearchParams.cs
> +        public int Page { get; set; } = DEFAULT_PAGE;
why we can not init property here and delete redundant const?

2018-12-21 08:55 UTC, AntonukOM commented on InternetHospital.WebApi/Controllers/FeedBackController.cs
> +                return NotFound(new { message = "Form not valid" });
form is not valid

2018-12-21 08:55 UTC, AntonukOM commented on InternetHospital.BusinessLogic/Services/FeedBackService.cs
> +            foreach (var item in feedBacks)
feedbacks not feedBacks

2018-12-21 08:55 UTC, AntonukOM commented on InternetHospital.BusinessLogic/Services/FeedBackService.cs
> -    public class FeedBackService : IFeedBackService
please rename to FeedbackService this class and methods with same names

2018-12-21 09:10 UTC, OleksandrAntoniuk approved these changes

2018-12-21 09:36 UTC, OleksandrAntoniuk approved these changes

2018-12-21 09:50 UTC, merged