Created home-page
Social-projects-Rivne/Internet-Hospital pull request #5
Opened 2018-10-10 07:25 UTC by SergiyKozachok

Added news-gallery into home-page

2018-10-10 08:10 UTC, TREN-D approved these changes

2018-10-10 14:12 UTC, serhiidotsyk approved these changes

2018-10-11 15:01 UTC, andriipetryna requested changes

2018-10-11 15:01 UTC, andriy-petryna commented on InternetHospitalWebUI/src/app/Components/Home/home/home.component.ts
> +  homeImages: HomeImages[] = [
Take out this hardcoded array to a constant in a separate file and create new service that returns this constant as an Observable object. This service will fetch real posts data from the server on the future.

2018-10-11 19:46 UTC, andriipetryna approved these changes

2018-10-11 19:51 UTC, merged