Feature/12 to design form for sign up possibility
Social-projects-Rivne/Internet-Hospital pull request #8
Opened 2018-10-13 19:02 UTC by SergiyKozachok

2018-10-14 12:35 UTC, andriipetryna requested changes

2018-10-14 12:35 UTC, andriipetryna commented on InternetHospitalWebUI/src/app/Components/Authorization/sign-up/sign-up.component.ts
> +      this.service.postUser(form.value).subscribe(res => console.log(res));
The result must be shown for a user in some way. If the registration failed - the user must see an error message.
Output to the console is redundant, remove it.

2018-10-14 12:35 UTC, andriipetryna commented on InternetHospitalWebUI/src/app/Services/authorization.service.ts
> +    console.log(body);
Output to the console is redundant, remove it.

2018-10-14 12:35 UTC, andriipetryna commented on InternetHospitalWebUI/src/app/Models/User.ts
> +    ConfirmPassword: string;
Confirm password field is unnecessary on the server side. If password and confirm password fields don't match - you can simply make registration button inactive in front-end. So if a user could send a registration data to the server it means his password fields match, and you will always get two similar passwords on the server side.

2018-10-14 12:35 UTC, andriy-petryna commented on InternetHospitalWebUI/src/app/config.ts
> +export const configUrl = 'https://localhost:44390';
Maybe it's better to rename configUrl variable to HOST_URL or ROOT_URL? 
And name constants in uppercase with underscore between words, please.

2018-10-14 12:35 UTC, andriy-petryna commented on InternetHospitalWebUI/src/app/Modules/routing/routing.module.ts
> +export const routingComponents = [
Rename constant to uppercase

2018-10-14 12:35 UTC, andriy-petryna commented on InternetHospitalWebUI/src/app/Components/Authorization/sign-up/sign-up.component.ts
> +  }
What the difference between `form.reset()` and `service.initializeFormGroup()` method where you simply assign empty values for form's inputs? Does not `form.reset()` make the same action?

2018-10-14 17:34 UTC, eugent482 commented
I think you should rename authorization.service to registration.service. Authorization is more about sign in.

2018-10-14 17:54 UTC, SergiyKozachok commented on InternetHospitalWebUI/src/app/Components/Authorization/sign-up/sign-up.component.ts
> +      this.service.postUser(form.value).subscribe(res => console.log(res));
Yes, we will create a nitificationService, and there will be a single format of notifications. But this is a separate task, and we will be obliged to do it in the next sprint

2018-10-14 17:56 UTC, SergiyKozachok commented on InternetHospitalWebUI/src/app/Models/User.ts
> +    ConfirmPassword: string;
I understand this, but Edik wants to do one more validation on the server, and he needs this field

2018-10-15 10:39 UTC, SergiyKozachok commented
> I think you should rename authorization.service to registration.service. Authorization is more about sign in.

I understand this, but it seems to me that on Sign Up and Sign In we can use one service. It is not necessary for each component to create a separate service

2018-10-15 13:52 UTC, andriipetryna approved these changes

2018-10-15 13:54 UTC, serhiidotsyk approved these changes

2018-10-15 13:54 UTC, TREN-D approved these changes

2018-10-15 13:55 UTC, merged